//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maui.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maui.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Me.
        /// </summary>
        public static string Click_Me {
            get {
                return ResourceManager.GetString("Click Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts the number of times you click.
        /// </summary>
        public static string Counts_the_number_of_times_you_click {
            get {
                return ResourceManager.GetString("Counts the number of times you click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string Create_Project {
            get {
                return ResourceManager.GetString("Create Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cute dot net bot waving hi to you!.
        /// </summary>
        public static string Cute_dot_net_bot_waving_hi_to_you_ {
            get {
                return ResourceManager.GetString("Cute dot net bot waving hi to you!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be empty.
        /// </summary>
        public static string Description_cannot_be_empty {
            get {
                return ResourceManager.GetString("Description cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to project.
        /// </summary>
        public static string Go_to_project {
            get {
                return ResourceManager.GetString("Go to project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, World!.
        /// </summary>
        public static string Hello__World_ {
            get {
                return ResourceManager.GetString("Hello, World!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Project.
        /// </summary>
        public static string List_Project {
            get {
                return ResourceManager.GetString("List Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project created successfully.
        /// </summary>
        public static string Project_created_successfully {
            get {
                return ResourceManager.GetString("Project created successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project details.
        /// </summary>
        public static string Project_details {
            get {
                return ResourceManager.GetString("Project details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string Project_name {
            get {
                return ResourceManager.GetString("Project name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name cannot be empty.
        /// </summary>
        public static string Project_name_cannot_be_empty {
            get {
                return ResourceManager.GetString("Project name cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code.
        /// </summary>
        public static string Status_Code {
            get {
                return ResourceManager.GetString("Status Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to .NET Multi-platform App UI.
        /// </summary>
        public static string Welcome_to__NET_Multi_platform_App_UI {
            get {
                return ResourceManager.GetString("Welcome to .NET Multi-platform App UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to dot net Multi platform App UI.
        /// </summary>
        public static string Welcome_to_dot_net_Multi_platform_App_UI {
            get {
                return ResourceManager.GetString("Welcome to dot net Multi platform App UI", resourceCulture);
            }
        }
    }
}
